### ISSUE TITLE
complete teshbvh.py functions

### ISSUE THREAD

**Issue by giangm9** [giangm9/bvh-am#2]
- Hoàn thành giao diện của chương trình theo mô tả ở trên drive, việc hỏi về thay đổi chức năng cũng như giải thích chức năng sẽ được làm thực hiện trước.
-  file testbvh.py sẽ thực hiện việc kiểm tra file bvh bằng cách nhận input từ dòng lệnh và dùng RuleManger để kiểm tra, không sử dụng trực tiếp Rule
- Việc thảo luận về các chức năng của RuleManger có thể được thực hiện song song với quá trình làm viết testbvh.py

**Comment by giangm9** [comment]
Renamed testbvh.py to validate.py

**Comment by dqt1995** [comment]
update validate.py
can be used
